#!/bin/sh
### BEGIN INIT INFO
# Provides:		ertza
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Ertza main process
### END INIT INFO
#
# Do not configure this file. Edit /etc/ertza/default.conf instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/ertza
NAME=ertza
DESC="Ertza main process"
PIDFILE=/var/run/ertza.pid

ERTZA_EXTRA_ARGS=
NO_START=0

set -e

test ! -r /etc/default/ertza || . /etc/default/ertza
test "$NO_START" = "0" || exit 0
test -x "$DAEMON" || exit 0
test ! -h /var/service/ertza || exit 0

readonly_rootfs=0
for flag in `awk '{ if ($2 == "/") { split($4,FLAGS,",") } }; END { for (f in FLAGS) print FLAGS[f] }' </proc/mounts`; do
  case $flag in
   ro)
     readonly_rootfs=1
     ;;
  esac
done


case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON"
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	sleep 1
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON"
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
