#!/bin/sh
### BEGIN INIT INFO
# Provides:		ertza
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Ertza program
### END INIT INFO
#
# Do not configure this file. Edit /etc/ertza/custom.conf instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/ertzad
NAME=ertza
DESC="Ertza for Armaz"
PIDFILE=/var/run/ertza.pid
ERTZA_ARGS='-f'

case "$1" in
  start)
	echo -n "Starting $DESC: "
        start-stop-daemon -S -p $PIDFILE \
           -x "$DAEMON" -- -p $PIDFILE $ERTZA_ARGS start
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        start-stop-daemon -K -p $PIDFILE -x "$DAEMON" -- -p $PIDFILE stop
        sleep 5
        killall -SIGTERM python3
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
        start-stop-daemon -S -p $PIDFILE \
           -x "$DAEMON" -- -p $PIDFILE $ERTZA_ARGS restart
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
