#!/bin/sh
### BEGIN INIT INFO
# Provides:		ertza
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Ertza program
### END INIT INFO
#
# Do not configure this file. Edit /etc/ertza/custom.conf instead!
#

LAUNCH_AS_DAEMON=0

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/ertzad
NAME=ertza
DESC="Ertza for Armaz"
PIDFILE=/var/run/ertza.pid
ERTZAD_ARGS='-f -e /dev/null -o /dev/null'

case "$1" in
  start)
	echo -n "Starting $DESC: "

        sleep 30
        (nohup /usr/bin/ertza > /dev/null 2>&1)&

	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        start-stop-daemon -K -p $PIDFILE -x "$DAEMON" -- -p $PIDFILE stop

        if [[ LAUNCH_AS_DAEMON == 1 ]]; then
            start-stop-daemon -K -p $PIDFILE \
               -x "$DAEMON" -- -p $PIDFILE stop
        else
            kill `cat $PIDFILE`
        fi
        sleep 5
        killall -SIGTERM python3
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "

        if [[ LAUNCH_AS_DAEMON == 1 ]]; then
            start-stop-daemon -S -p $PIDFILE \
               -x "$DAEMON" -- -p $PIDFILE $ERTZA_ARGS restart
        fi
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
